---
- hosts: 172.31.14.184
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
      notify: restartwebservers

  - name: i want to copy static file into
    copy:
          src: mystaticfile.html
          dest: /var/www/html/index.html
        
  - name: i want to install dynamic file into node
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    ignore_errors: yes

  - name: i want to create a folder
    file:
      path: /home/ubuntu/myfolder
      state: directory



  - name: i want to download files from the remote(internet) into the nodes side
    get_url:
        url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
        dest: /home/maha/jenkins.war
        force_basic_auth: yes
        notify: restartwebservers


  handlers: 
  - name: restartwebservers
    service:
      name: apache2
      state: restarted


