---
- hosts: 172.31.14.184
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy static file into
    copy:
          src: mystaticfile.html
          dest: /var/www/html/index.html
              